# Stage 1: Build the application
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code
COPY src ./src

# Package the app without tests
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copy only the packaged JAR
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8060

# Start the Spring Boot application
CMD ["java", "-jar", "app.jar"]
