FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

# Copy pom.xml
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline

# Copy source code
COPY src ./src

EXPOSE 8060

# Run the application using Maven
CMD ["mvn", "spring-boot:run"] 